version: "3.9"

services:

  backend:
    build: ./Backend
    container_name: ept-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    restart: always

  frontend:
    build: ./Frontend
    container_name: ept-frontend
    ports:
      - "3000:80"
    restart: always