# Generated by Django 5.2.8 on 2026-03-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ept', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
